In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


In [14]:
cleanmeta = pd.read_csv("actormetaMonths.csv")
cleanmeta = cleanmeta[['budget','revenue','popularity','runtime','castRevBudRatio','january','february','march','april','may','june','july','august','september','october','november','december']]
cleanmeta = cleanmeta.dropna()
cleanmeta = cleanmeta.reset_index()
X = cleanmeta.values
y = cleanmeta['revenue']/cleanmeta['budget'].values

In [15]:
cleanmeta[0:1]

index      budget      revenue  popularity  runtime  castRevBudRatio  \
0      0  30000000.0  373554033.0   21.946943     81.0         7.791539   

   january  february  march  april  may  june  july  august  september  \
0        0         0      0      0    0     0     0       0          0   

   october  november  december  
0        1         0         0

In [12]:
for i in range(0,len(y)):
    if y[i] > 1:
        y[i] = 0 #success
    else:
        y[i] = 1 #failure

In [25]:
X_train = X[:4500]
X_test = X[4500:]

y_train = y[:4500]
y_test = y[4500:]

In [26]:
len(X_train)

4500

In [27]:
len(y_train)

4500

In [28]:
type(X_train[0])

numpy.ndarray

In [29]:
X[0:10]

array([[30000000.0, 373554033.0, 21.946943],
       [65000000.0, 262797249.0, 17.015539],
       [16000000.0, 81452156.0, 3.859495],
       [60000000.0, 187436818.0, 17.924927],
       [35000000.0, 64350171.0, 5.23158],
       [58000000.0, 352194034.0, 14.686035999999998],
       [62000000.0, 107879496.0, 6.318445],
       [44000000.0, 13681765.0, 5.092],
       [98000000.0, 10017322.0, 7.284477000000001],
       [52000000.0, 116112375.0, 10.137389]], dtype=object)

In [30]:
y[0:10]

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0.])

In [31]:

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train,y_train)



GaussianNB(priors=None)

In [32]:
y_pred =clf.predict(X_test)



In [33]:
ab = sorted(y_pred)

In [37]:
clf.theta_ 

array([[3.40614692e+07, 1.21494276e+08, 1.01581402e+01],
       [2.50037710e+07, 1.28227295e+07, 6.81245713e+00]])

In [39]:
#print('Coefficients: \n', clf.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Mean squared error: 0.35
Variance score: -0.62
