In [46]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.svm import SVR


In [47]:
metadata = pd.read_csv("the-movies-dataset/movies_metadata.csv")
cleanmeta = metadata[(metadata['adult'] == 'False') & (metadata['revenue'] != 0)  &(metadata['status'] == 'Released')]
cleanmeta['budget'] = cleanmeta.budget.astype(float)
#leanmeta.dtype
cleanmeta2 = cleanmeta[(cleanmeta['budget'] != 0 )]
rb = cleanmeta2[['budget','revenue','popularity']]
rb['r/b'] = rb['revenue']/rb['budget']
X =rb[['budget','revenue','popularity']].values
y = rb['r/b'].values

C:\Users\woosung\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\woosung\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\woosung\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-vie

In [49]:
X_train = X[:4500]
X_test = X[4500:]

y_train = y[:4500]
y_test = y[4500:]

In [50]:
X_train[0:5]

array([[30000000.0, 373554033.0, 21.946943],
       [65000000.0, 262797249.0, 17.015539],
       [16000000.0, 81452156.0, 3.859495],
       [60000000.0, 187436818.0, 17.924927],
       [35000000.0, 64350171.0, 5.23158]], dtype=object)

In [51]:
y_train[0:5]

array([12.4518011 ,  4.0430346 ,  5.09075975,  3.12394697,  1.83857631])

In [52]:
X_train = np.array(X_train)
y_train = np.array(y_train)

In [53]:

#clf = SVC(kernel = 'linear', C = 1.0)
#clf.fit(X_train, y_train) 
#y_train = y_train.reshape(1, -1)
clf=SVR()
clf.fit(X_train,y_train)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
clf = SVC(gamma='auto')
clf.fit(X, y) 

In [16]:
X_train[0:4]

array([[30000000.0, 373554033.0, 21.946943],
       [65000000.0, 262797249.0, 17.015539],
       [16000000.0, 81452156.0, 3.859495],
       [60000000.0, 187436818.0, 17.924927]], dtype=object)

In [67]:
print(X_test[0])
print(y_test[0:10])

[100000000.0 243400000.0 19.606895]
[2.434      2.103657   0.99696345 3.48461538 1.91479213 0.03678042
 0.18738147 3.03746196 4.04003732 1.04538477]


In [59]:
result = clf.predict(X_test)

In [68]:
result[0:10]

array([2.12122205, 2.12122205, 2.12122205, 2.12122205, 2.12122205,
       2.12122205, 2.12122205, 2.12122205, 2.12122205, 2.12122205])